name: Deploy ACA Image
run-name: deploy hello-world to dev ACA

on:
  workflow_dispatch:
permissions:
  contents: read
  id-token: write

env:
  IMAGE_TO_DEPLOY: "mcr.microsoft.com/azuredocs/containerapps-helloworld:latest"
  CONTAINER_APP_NAME: "ca-myapp-1-dev-weu"
  RESOURCE_GROUP: "rg-platform-noncritical-dev-weu"
  CONTAINER_APP_ENVIRONMENT: "cae-platform-noncritical-dev-weu"
  LOCATION: "westeurope"
  YAML_CONFIG_PATH: ".github/containerapps/hello-world-dev.yaml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy ACA Image
    environment: dev
    steps:
      - name: Azure login
        uses: azure/login@v2.3.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Deploy hello-world image
        uses: azure/container-apps-deploy-action@v2
        with:
          imageToDeploy: ${{ env.IMAGE_TO_DEPLOY }}
          containerAppName: ${{ env.CONTAINER_APP_NAME }}
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          containerAppEnvironment: ${{ env.CONTAINER_APP_ENVIRONMENT }}
          location: ${{ env.LOCATION }}
          disableTelemetry: true
          minReplicas: 1
          maxReplicas: 1
